### ISSUE TITLE
Grids do not display properly

### ISSUE THREAD

**Issue by elifoster** [HydraWiki/OreDict#26]
Take a look at http://ftb.gamepedia.com/Carving_Table#Recipe to see what I mean. It looks like some SQL querying in the parser function doesn't work properly. However, the only difference I found in #20 was that we use 'ext_oredict_items' rather than `$dbr->tableName('ext_oredict_items');`, and `$sLim` is now purely the output limit, rather than `"LIMIT 0,".outputLimit`. I'm not really sure how either of these would actually cause the issue, though.

**Comment by Chocohead** [comment]
Um Santa, you mean http://ftb.gamepedia.com/Carving_Table#Recipe

**Comment by elifoster** [comment]
From #28:



E_ERROR: Maximum execution time of 30 seconds exceeded

…ItemName called at /home/hydra/public_html/extensions/OreDict/OreDict.body.php (415)
…ItemName called at /home/hydra/public_html/extensions/OreDict/OreDict.body.php (239)
…t::exec called at /home/hydra/public_html/extensions/OreDict/OreDict.hooks.php (185)
in OreDictHooks::RenderParser called at ? (?)


[11:46:16] <Trela> This would have been at line 415:	public function getItemName() { return $this->mItemName; }

That function is called in the Tilesheets extension hook thingy.
…l_user_func_array called at /home/hydra/public_html/includes/parser/Parser.php (3789)
…allParserFunction called at /home/hydra/public_html/includes/parser/Parser.php (3523)
…itution called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1177)
…at /home/hydra/public_html/extensions/ParserFunctions/ParserFunctions_body.php (104)
in ExtParserFunctions::ifObj called at ? (?)
…l_user_func_array called at /home/hydra/public_html/includes/parser/Parser.php (3789)
…allParserFunction called at /home/hydra/public_html/includes/parser/Parser.php (3523)
…itution called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1177)
…Frame_DOM::expand called at /home/hydra/public_html/includes/parser/Parser.php (3665)
…itution called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1177)
…:expand called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1687)
…rgument called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1695)
…_DOM::getArgument called at /home/hydra/public_html/includes/parser/Parser.php (4161)
…itution called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1196)
…:expand called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1675)
…rgument called at /home/hydra/public_html/includes/parser/Preprocessor_DOM.php (1693)

Where

**Comment by elifoster** [comment]
I think this may actually be caused by Tilesheets, as that is what does the actual rendering of the tiles. OreDict's parser function just runs a hook.

**Comment by elifoster** [comment]
It looks like this isn't actually fixed, although it is likely caused by the Tilesheets extension now.
