### ISSUE TITLE
Pagination broken in OreDictList

### ISSUE THREAD

**Issue by retep998** [HydraWiki/OreDict#9]
I already had a working fix but it's buried in a mess of other commits.
If someone could extract the relevant changes and clean them up a bit, that would be appreciated.

https://github.com/CurseStaff/OreDict/commit/4009019447b443086bbbcb46b1ac1b49d1af4deb
https://github.com/CurseStaff/OreDict/commit/b33820204205b6cc3d96acc8152bb0dcb1b8699b

**Comment by Alexia** [comment]
I put this on the internal JIRA tracker to be worked on.  I am unsure of the time frame for it.

**Comment by elifoster** [comment]
See #22.
